
const companies = [
    {
      logoImage:"https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/102020/logo.png?_yoy9w6Odc3ZcujdWnFOI7Tv.JqxzkZF&itok=tZFwmDM_",
      id: 1,
      name: 'Wisedoc, Inc.',
      position: 'Frontend Developer',
      location: 'India (Remote)',
      responsibilities: ['Develop user interfaces', 'Collaborate with designers'],
      qualifications: ['HTML', 'CSS', 'JavaScript', 'React or Vue.js'],
      benefits: ['Competitive salary', 'Flexible remote work', 'Health insurance'],
      employees: 150,
      projects: ['Project A - E-commerce Platform', 'Project B - Blogging Application', 'Project C - Social Networking App'],
      achievements: [
        '2019 - Best Web Development Company Award',
        '2020 - Top 10 Companies for Remote Work',
        '2021 - Excellence in User Interface Design',
      ],
      foundedYear: 2010,
      website: 'https://www.wisedoc.com',
      contactEmail: 'info@wisedoc.com',
      technologiesUsed: ['React', 'Node.js', 'MongoDB', 'AWS'],
      partnerships: ['Google', 'Microsoft', 'Adobe'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/wisedoc',
        twitter: 'https://twitter.com/wisedocinc',
        facebook: 'https://www.facebook.com/wisedoc',
      },
      companySize: 'Medium',
      industry: 'Technology',
      awards: ['2022 - Best Workplace Diversity Award', '2023 - Innovation Excellence'],
      offices: [
        {
          city: 'Bangalore',
          country: 'India',
        },
        {
          city: 'New York',
          country: 'United States',
        },
      ],
      founders: ['John Doe', 'Jane Smith'],
      about: 'Wisedoc, Inc. is a leading technology company specializing in web development and user interface design. Our mission is to create innovative solutions that empower businesses to thrive in the digital landscape. With a team of dedicated professionals and a commitment to excellence, we have garnered several awards and recognition for our outstanding contributions to the industry.',
      aboutCulture: 'At Wisedoc, we foster a culture of collaboration, creativity, and diversity. Our team members come from diverse backgrounds, bringing unique perspectives to the table. We believe in continuous learning and provide opportunities for professional growth. Our inclusive and supportive work environment encourages creativity and innovation.',
      aboutValues: ['Innovation', 'Collaboration', 'Diversity', 'Excellence'],
      aboutPerks: ['Flexible work hours', 'Professional development opportunities', 'Health and wellness programs'],
    },
    // Add 19 more companies here...
  
    {
      logoImage:"https://techgeniussolution.com/img/logo/logo2.png",
      id: 2,
      name: 'TechGenius Solutions',
      position: 'Full Stack Developer',
      location: 'United States (On-site)',
      responsibilities: ['Design and implement software solutions', 'Collaborate with cross-functional teams'],
      qualifications: ['Web development technologies', 'Backend frameworks (e.g., Node.js)'],
      benefits: ['401(k) plan', 'Health and dental coverage', 'Professional development opportunities'],
      employees: 200,
      projects: ['Project X - Enterprise System Integration', 'Project Y - Mobile App Development'],
      achievements: [
        '2018 - Outstanding Achievement in Software Development',
        '2019 - Best Tech Workplace in the US',
        '2020 - Innovation Excellence Award',
      ],
      foundedYear: 2005,
      website: 'https://www.techgenius.com',
      contactEmail: 'info@techgenius.com',
      technologiesUsed: ['React', 'Angular', 'Spring Boot', 'AWS'],
      partnerships: ['IBM', 'Salesforce', 'Oracle'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/techgenius',
        twitter: 'https://twitter.com/techgeniusco',
        facebook: 'https://www.facebook.com/techgenius',
      },
      companySize: 'Large',
      industry: 'Information Technology',
      awards: ['2017 - Best Tech Innovation Award', '2019 - Top Software Development Company'],
      offices: [
        {
          city: 'San Francisco',
          country: 'United States',
        },
        {
          city: 'New York',
          country: 'United States',
        },
      ],
      founders: ['Alex Johnson', 'Emily Davis'],
      about: 'TechGenius Solutions is a leading IT company dedicated to providing cutting-edge software solutions. Our team of experts thrives on challenges and is committed to delivering high-quality products to our clients. We pride ourselves on innovation, collaboration, and a strong commitment to excellence.',
      aboutCulture: 'Our company culture is built on a foundation of collaboration, innovation, and continuous learning. We value diversity and inclusion, fostering an environment where every team member\'s unique talents are recognized and appreciated. Join us in shaping the future of technology!',
      aboutValues: ['Innovation', 'Collaboration', 'Quality', 'Customer-Centricity'],
      aboutPerks: ['Competitive salary', 'Flexible work hours', 'Health and wellness programs'],
      employees: 200,
      projects: ['Project X - Enterprise System Integration', 'Project Y - Mobile App Development'],
      achievements: [
        '2018 - Outstanding Achievement in Software Development',
        '2019 - Best Tech Workplace in the US',
        '2020 - Innovation Excellence Award',
      ],
      foundedYear: 2005,
      website: 'https://www.techgenius.com',
      contactEmail: 'info@techgenius.com',
      technologiesUsed: ['React', 'Angular', 'Spring Boot', 'AWS'],
      partnerships: ['IBM', 'Salesforce', 'Oracle'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/techgenius',
        twitter: 'https://twitter.com/techgeniusco',
        facebook: 'https://www.facebook.com/techgenius',
      },
      companySize: 'Large',
      industry: 'Information Technology',
      awards: ['2017 - Best Tech Innovation Award', '2019 - Top Software Development Company'],
      offices: [
        {
          city: 'San Francisco',
          country: 'United States',
        },
        {
          city: 'New York',
          country: 'United States',
        },
      ],
      founders: ['Alex Johnson', 'Emily Davis'],
      about: 'TechGenius Solutions is a leading IT company dedicated to providing cutting-edge software solutions. Our team of experts thrives on challenges and is committed to delivering high-quality products to our clients. We pride ourselves on innovation, collaboration, and a strong commitment to excellence.',
      aboutCulture: 'Our company culture is built on a foundation of collaboration, innovation, and continuous learning. We value diversity and inclusion, fostering an environment where every team member\'s unique talents are recognized and appreciated. Join us in shaping the future of technology!',
      aboutValues: ['Innovation', 'Collaboration', 'Quality', 'Customer-Centricity'],
      aboutPerks: ['Competitive salary', 'Flexible work hours', 'Health and wellness programs'],
    },
    {
      logoImage:"https://innovatexconz.files.wordpress.com/2021/05/cropped-cropped-cropped-1234-1.png",
      id: 3,
      name: 'InnovateTech Labs',
      position: 'Data Scientist',
      location: 'Singapore (Remote)',
      responsibilities: ['Analyzing and interpreting complex data sets', 'Developing custom data models'],
      qualifications: ['Strong statistical and programming skills', 'Experience with machine learning frameworks'],
      benefits: ['Remote work options', 'Competitive salary', 'Health and wellness programs'],
      employees: 50,
      projects: ['Project Z - Predictive Analytics Platform', 'Project W - Customer Segmentation'],
      achievements: [
        '2019 - Excellence in Data Science',
        '2020 - Top Remote Work Company',
        '2021 - Best Data Science Team',
      ],
      foundedYear: 2015,
      website: 'https://www.innovatetechlabs.com',
      contactEmail: 'info@innovatetechlabs.com',
      technologiesUsed: ['Python', 'TensorFlow', 'Scikit-Learn', 'Big Data Technologies'],
      partnerships: ['Microsoft', 'Google Cloud', 'IBM'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/innovatetechlabs',
        twitter: 'https://twitter.com/innovatetech',
        facebook: 'https://www.facebook.com/innovatetechlabs',
      },
      companySize: 'Small',
      industry: 'Data Science',
      awards: ['2022 - Best Data Science Innovations', '2023 - Top Data Science Company'],
      offices: [
        {
          city: 'Singapore',
          country: 'Singapore',
        },
      ],
      founders: ['James Tan', 'Linda Lim'],
      about: 'InnovateTech Labs specializes in data science, providing advanced analytics solutions for businesses. Our team of skilled data scientists is passionate about extracting valuable insights from complex datasets, helping organizations make informed decisions. We are committed to pushing the boundaries of data science innovation.',
      aboutCulture: 'At InnovateTech Labs, we foster a culture of curiosity, innovation, and collaboration. Our data science team is encouraged to explore new methodologies and stay abreast of the latest advancements in the field. We value diversity and believe that a mix of backgrounds enhances our problem-solving capabilities.',
      aboutValues: ['Innovation', 'Curiosity', 'Collaboration', 'Data-Driven Decision Making'],
      aboutPerks: ['Remote work options', 'Professional development opportunities', 'Health and wellness programs'],
    },
    {
      logoImage:"https://codecrafterspune.com/assets/img/codecrafters.jpg",
      id: 4,
      name: 'CodeCrafters Ltd.',
      position: 'UX/UI Designer',
      location: 'Canada (Remote)',
      responsibilities: ['Create visually appealing user interfaces', 'Collaborate with product managers'],
      qualifications: ['Proven experience in UX/UI design', 'Familiarity with design tools (e.g., Sketch, Figma)'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Generous vacation policy'],
      employees: 80,
      projects: ['Project U - Redesign of E-commerce Platform', 'Project V - Mobile App User Interface'],
      achievements: [
        '2018 - Best UX/UI Design Team',
        '2019 - Excellence in Visual Design',
        '2020 - Top Remote Design Company',
      ],
      foundedYear: 2011,
      website: 'https://www.codecrafters.com',
      contactEmail: 'info@codecrafters.com',
      technologiesUsed: ['Sketch', 'Figma', 'Adobe XD'],
      partnerships: ['InVision', 'Dribbble', 'Behance'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/codecrafters',
        twitter: 'https://twitter.com/codecrafters',
        facebook: 'https://www.facebook.com/codecraftersdesign',
      },
      companySize: 'Medium',
      industry: 'Design',
      awards: ['2022 - Best User-Centric Design', '2023 - Innovation in Visual Design'],
      offices: [
        {
          city: 'Toronto',
          country: 'Canada',
        },
        {
          city: 'Vancouver',
          country: 'Canada',
        },
      ],
      founders: ['Sarah Johnson', 'Michael Lee'],
      about: 'CodeCrafters Ltd. is a design-focused company dedicated to creating exceptional user experiences. Our team of UX/UI designers is passionate about crafting visually appealing and user-friendly interfaces that enhance digital products. We believe in the power of design to transform ideas into engaging and impactful experiences.',
      aboutCulture: 'At CodeCrafters, we foster a culture of creativity, collaboration, and innovation. Our design team is encouraged to push boundaries and explore new design trends. We value diversity and believe that a mix of perspectives contributes to the richness of our design solutions.',
      aboutValues: ['Creativity', 'Collaboration', 'User-Centric Design', 'Innovation'],
      aboutPerks: ['Remote work flexibility', 'Professional development opportunities', 'Health and wellness programs'],
    },
    // Add 16 more companies here...
    {
      logoImage:"https://lesvallons.com/images/2042636.png",
      id: 5,
      name: 'WebMasters Co.',
      position: 'SEO Specialist',
      location: 'Australia (On-site)',
      responsibilities: ['Optimize website content for search engines', 'Analyze and implement SEO strategies'],
      qualifications: ['Experience in SEO optimization', 'Familiarity with SEO tools'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 120,
      projects: ['Project SEO - Website Optimization for E-commerce Platform', 'Project Analytics - SEO Data Analysis'],
      achievements: [
        '2017 - Outstanding SEO Implementation',
        '2018 - Top SEO Specialist Award',
        '2019 - Excellence in Search Engine Optimization',
      ],
      foundedYear: 2008,
      website: 'https://www.webmastersco.com',
      contactEmail: 'info@webmastersco.com',
      technologiesUsed: ['Google Analytics', 'SEMrush', 'Moz'],
      partnerships: ['Google', 'Ahrefs', 'Yoast'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/webmastersco',
        twitter: 'https://twitter.com/webmastersco',
        facebook: 'https://www.facebook.com/webmastersco',
      },
      companySize: 'Medium',
      industry: 'Digital Marketing',
      awards: ['2021 - Best SEO Implementation', '2022 - Top SEO Company'],
      offices: [
        {
          city: 'Sydney',
          country: 'Australia',
        },
        {
          city: 'Melbourne',
          country: 'Australia',
        },
      ],
      founders: ['David Smith', 'Emily Turner'],
      about: 'WebMasters Co. is a leading digital marketing company specializing in search engine optimization (SEO). Our team of SEO specialists is dedicated to optimizing website content and implementing effective strategies to improve online visibility. We are committed to helping businesses achieve higher rankings and attract organic traffic.',
      aboutCulture: 'At WebMasters, we foster a culture of collaboration, innovation, and continuous learning. Our SEO specialists stay updated with the latest industry trends and search engine algorithms. We value diversity and believe that a dynamic team enhances our ability to deliver outstanding SEO results.',
      aboutValues: ['Excellence in SEO', 'Collaboration', 'Continuous Learning', 'Data-Driven Decisions'],
      aboutPerks: ['On-site work environment', 'Professional development opportunities', 'Health and wellness programs'],
    },
    {
      logoImage:"https://www.softinnovationbd.com/assets/softinnovation_logo.f6eafe31.png",
      id: 6,
      name: 'SoftInnovate Solutions',
      position: 'Software Engineer',
      location: 'Germany (Remote)',
      responsibilities: ['Design and implement software solutions', 'Collaborate with development teams'],
      qualifications: ['Proficiency in programming languages', 'Experience with software development methodologies'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
      employees: 150,
      projects: ['Project A - Enterprise Software Development', 'Project B - Mobile App Integration'],
      achievements: [
        '2019 - Outstanding Software Development Team',
        '2020 - Excellence in Coding Practices',
        '2021 - Top Remote Software Engineering Company',
      ],
      foundedYear: 2010,
      website: 'https://www.softinnovate.com',
      contactEmail: 'info@softinnovate.com',
      technologiesUsed: ['Java', 'Python', 'React', 'Node.js'],
      partnerships: ['Microsoft', 'GitHub', 'AWS'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/softinnovate',
        twitter: 'https://twitter.com/softinnovate',
        facebook: 'https://www.facebook.com/softinnovate',
      },
      companySize: 'Medium',
      industry: 'Software Development',
      awards: ['2022 - Best Remote Software Development Team', '2023 - Innovation in Software Engineering'],
      offices: [
        {
          city: 'Berlin',
          country: 'Germany',
        },
        {
          city: 'Munich',
          country: 'Germany',
        },
      ],
      founders: ['Markus Schmidt', 'Anna Müller'],
      about: 'SoftInnovate Solutions is a dynamic software development company that specializes in creating innovative solutions. Our team of dedicated software engineers is passionate about delivering high-quality software products. We embrace remote work and believe in providing a flexible and collaborative environment for our team.',
      aboutCulture: 'At SoftInnovate, we foster a culture of innovation, collaboration, and continuous learning. Our software engineers are encouraged to explore new technologies and contribute ideas to enhance our products. We value diversity and believe in creating a workplace where every team member can thrive.',
      aboutValues: ['Innovation', 'Collaboration', 'Quality', 'Continuous Learning'],
      aboutPerks: ['Remote work flexibility', 'Professional development opportunities', 'Health and wellness programs'],
    },
  
    {
      logoImage:"https://www.ecotech-innovation.fr/data/themes/ecotech-innovation/images/xlogo.png.pagespeed.ic.q5PRubm4VT.png",
      id: 7,
      name: 'EcoTech Innovations',
      position: 'Environmental Analyst',
      location: 'Brazil (On-site)',
      responsibilities: ['Analyze environmental data', 'Contribute to sustainability initiatives'],
      qualifications: ['Degree in Environmental Science', 'Experience in data analysis'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 80,
      projects: ['Project Eco - Biodiversity Conservation Analysis', 'Project Green - Sustainable Practices Implementation'],
      achievements: [
        '2018 - Excellence in Environmental Analysis',
        '2019 - Top Environmental Analyst Team',
        '2020 - Green Innovation Award',
      ],
      foundedYear: 2012,
      website: 'https://www.ecotechinnovations.com',
      contactEmail: 'info@ecotechinnovations.com',
      technologiesUsed: ['GIS', 'Data Visualization Tools', 'Environmental Modeling Software'],
      partnerships: ['UN Environment', 'World Wildlife Fund (WWF)', 'Greenpeace'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/ecotechinnovations',
        twitter: 'https://twitter.com/ecotechinnovate',
        facebook: 'https://www.facebook.com/ecotechinnovations',
      },
      companySize: 'Medium',
      industry: 'Environmental Science',
      awards: ['2021 - Sustainability Excellence Award', '2022 - Top Environmental Science Company'],
      offices: [
        {
          city: 'São Paulo',
          country: 'Brazil',
        },
        {
          city: 'Rio de Janeiro',
          country: 'Brazil',
        },
      ],
      founders: ['Carlos Silva', 'Maria Oliveira'],
      about: 'EcoTech Innovations is a leading environmental science company dedicated to analyzing and promoting sustainable practices. Our team of environmental analysts works towards understanding and mitigating environmental impacts. We are committed to making a positive contribution to the environment and creating a greener future.',
      aboutCulture: 'At EcoTech, we foster a culture of environmental stewardship, collaboration, and impact-driven work. Our environmental analysts are passionate about making a difference in the world. We value diversity and believe in collective efforts to address global environmental challenges.',
      aboutValues: ['Sustainability', 'Environmental Stewardship', 'Collaboration', 'Impact-Driven Work'],
      aboutPerks: ['On-site work environment', 'Professional development opportunities', 'Health and wellness programs'],
    },
    {
      logoImage:"https://images.squarespace-cdn.com/content/v1/5b0dfd31372b967956a2fc47/1527643532917-HTXEP4SFU6VT894X63DR/fintech+logo+%281%29.png",
      id: 8,
      name: 'FinTech Solutions Ltd.',
      position: 'Financial Analyst',
      location: 'United Kingdom (Remote)',
      responsibilities: ['Analyze financial data', 'Contribute to financial planning'],
      qualifications: ['Degree in Finance or related field', 'Experience in financial analysis'],
      benefits: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
      employees: 100,
      projects: ['Project Finance - Financial Data Analysis', 'Project Planning - Financial Strategy Development'],
      achievements: [
        '2020 - Excellence in Financial Analysis',
        '2021 - Top Remote Financial Analyst Team',
        '2022 - Best Financial Planning Contribution',
      ],
      foundedYear: 2013,
      website: 'https://www.fintechsolutions.com',
      contactEmail: 'info@fintechsolutions.com',
      technologiesUsed: ['Excel', 'Financial Modeling Software', 'Data Analytics Tools'],
      partnerships: ['Bloomberg', 'Reuters', 'Financial Times'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/fintechsolutions',
        twitter: 'https://twitter.com/fintechsolutions',
        facebook: 'https://www.facebook.com/fintechsolutions',
      },
      companySize: 'Medium',
      industry: 'Financial Technology',
      awards: ['2023 - Top Financial Technology Company', '2024 - Innovation in Financial Analytics'],
      offices: [
        {
          city: 'London',
          country: 'United Kingdom',
        },
        {
          city: 'Manchester',
          country: 'United Kingdom',
        },
      ],
      founders: ['Oliver Turner', 'Sophie Harris'],
      about: 'FinTech Solutions Ltd. is a financial technology company that specializes in providing innovative solutions for financial analysis and planning. Our team of financial analysts is committed to delivering accurate and insightful financial data analysis. We embrace remote work and offer a flexible and collaborative environment for our team.',
      aboutCulture: 'At FinTech Solutions, we foster a culture of precision, innovation, and continuous improvement. Our financial analysts are encouraged to stay updated with the latest financial trends and tools. We value diversity and believe in providing a workplace where each team member can contribute to our collective success.',
      aboutValues: ['Precision', 'Innovation', 'Collaboration', 'Continuous Improvement'],
      aboutPerks: ['Remote work options', 'Professional development opportunities', 'Health and wellness programs'],
    },
  
    {
      logoImage:"https://www.biospectrumasia.com/uploads/articles/medtechinnovator_accelerator_social-17002.png",
      id: 9,
      name: 'MedTech Innovators',
      position: 'Biomedical Engineer',
      location: 'Spain (On-site)',
      responsibilities: ['Design and develop medical devices', 'Collaborate with healthcare professionals'],
      qualifications: ['Degree in Biomedical Engineering', 'Experience in medical device development'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 60,
      projects: ['Project MedTech - Advanced Medical Imaging Device', 'Project Health - Wearable Health Technology'],
      achievements: [
        '2019 - Excellence in Biomedical Engineering',
        '2020 - Top Biomedical Engineering Team',
        '2021 - Innovation in Medical Device Development',
      ],
      foundedYear: 2014,
      website: 'https://www.medtechinnovators.com',
      contactEmail: 'info@medtechinnovators.com',
      technologiesUsed: ['CAD Software', 'LabVIEW', 'Biocompatible Materials'],
      partnerships: ['World Health Organization (WHO)', 'Medical Device Manufacturers Association'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/medtechinnovators',
        twitter: 'https://twitter.com/medtechinnovate',
        facebook: 'https://www.facebook.com/medtechinnovators',
      },
      companySize: 'Medium',
      industry: 'Healthcare Technology',
      awards: ['2022 - Top Medical Technology Company', '2023 - Excellence in Healthcare Innovation'],
      offices: [
        {
          city: 'Barcelona',
          country: 'Spain',
        },
        {
          city: 'Madrid',
          country: 'Spain',
        },
      ],
      founders: ['Antonio Rodriguez', 'Elena Gomez'],
      about: 'MedTech Innovators is a pioneering company in the field of biomedical engineering, dedicated to designing and developing innovative medical devices. Our team of biomedical engineers is passionate about creating solutions that advance healthcare technology. We are committed to making a positive impact on the lives of patients and healthcare professionals.',
      aboutCulture: 'At MedTech Innovators, we foster a culture of innovation, collaboration, and patient-centric design. Our biomedical engineers are encouraged to explore new technologies and contribute to advancements in medical science. We value diversity and believe that a collaborative approach enhances our ability to create groundbreaking solutions.',
      aboutValues: ['Innovation', 'Collaboration', 'Patient-Centric Design', 'Advancement in Medical Science'],
      aboutPerks: ['On-site work environment', 'Professional development opportunities', 'Health and wellness programs'],
    },
    {
      logoImage:"https://fts.bio/wp-content/uploads/2023/01/fts-logo.jpeg",
      id: 10,
      name: 'FoodieTech Solutions',
      position: 'Mobile App Developer',
      location: 'France (Remote)',
      responsibilities: ['Develop mobile applications', 'Collaborate with UX/UI designers'],
      qualifications: ['Proficiency in mobile app development', 'Experience with iOS and Android platforms'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
      employees: 80,
      projects: ['Project Foodie - Food Delivery App', 'Project Recipe - Cooking and Recipe Sharing App'],
      achievements: [
        '2021 - Top Mobile App Developer Team',
        '2022 - Excellence in Mobile App Development',
        '2023 - Innovation in User Experience'],
      foundedYear: 2015,
      website: 'https://www.foodietechsolutions.com',
      contactEmail: 'info@foodietechsolutions.com',
      technologiesUsed: ['React Native', 'Swift', 'Kotlin'],
      partnerships: ['App Store', 'Google Play', 'Firebase'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/foodietechsolutions',
        twitter: 'https://twitter.com/foodietech',
        facebook: 'https://www.facebook.com/foodietechsolutions',
      },
      companySize: 'Medium',
      industry: 'Mobile App Development',
      awards: ['2023 - Top Mobile App Development Company', '2024 - Innovation in App Design'],
      offices: [
        {
          city: 'Paris',
          country: 'France',
        },
        {
          city: 'Marseille',
          country: 'France',
        },
      ],
      founders: ['Julien Martin', 'Sophie Leroy'],
      about: 'FoodieTech Solutions is a leading mobile app development company specializing in creating innovative and user-friendly mobile applications. Our team of mobile app developers is passionate about delivering high-quality and engaging apps for various platforms. We embrace remote work and offer a collaborative and dynamic environment for our team.',
      aboutCulture: 'At FoodieTech, we foster a culture of creativity, collaboration, and passion for technology. Our mobile app developers are encouraged to explore new ideas and stay updated with the latest trends in mobile app development. We value diversity and believe in creating a workplace where innovation thrives.',
      aboutValues: ['Creativity', 'Collaboration', 'Passion for Technology', 'User-Centric Design'],
      aboutPerks: ['Remote work flexibility', 'Professional development opportunities', 'Health and wellness programs'],
    },
  
    {
      logoImage:"https://www.onshelf.co.za/wp-content/uploads/2019/07/AI-Innovations-in-the-World-of-Learning-and-Disability-1-1.jpg",
      id: 11,
      name: 'AI Innovations Co.',
      position: 'Machine Learning Engineer',
      location: 'South Korea (On-site)',
      responsibilities: ['Design and implement machine learning models', 'Collaborate with data scientists'],
      qualifications: ['Degree in Computer Science or related field', 'Experience in machine learning'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 120,
      projects: ['Project AI - Advanced Machine Learning Algorithms', 'Project DeepLearning - Neural Network Development'],
      achievements: [
        '2018 - Top Machine Learning Team',
        '2019 - Innovation in AI Research',
        '2020 - Excellence in Neural Network Implementation'],
      foundedYear: 2011,
      website: 'https://www.aiinnovationsco.com',
      contactEmail: 'info@aiinnovationsco.com',
      technologiesUsed: ['TensorFlow', 'PyTorch', 'Scikit-Learn'],
      partnerships: ['OpenAI', 'NVIDIA', 'Samsung Research'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/aiinnovationsco',
        twitter: 'https://twitter.com/aiinnovations',
        facebook: 'https://www.facebook.com/aiinnovationsco',
      },
      companySize: 'Large',
      industry: 'Artificial Intelligence',
      awards: ['2021 - Top AI Research Company', '2022 - Excellence in Machine Learning'],
      offices: [
        {
          city: 'Seoul',
          country: 'South Korea',
        },
        {
          city: 'Busan',
          country: 'South Korea',
        },
      ],
      founders: ['Joon-Ho Kim', 'Eun-Ji Park'],
      about: 'AI Innovations Co. is a pioneering company in the field of artificial intelligence, dedicated to designing and implementing advanced machine learning models. Our team of machine learning engineers is passionate about pushing the boundaries of AI research and development. We believe in the power of AI to transform industries and improve the way we live.',
      aboutCulture: 'At AI Innovations, we foster a culture of curiosity, collaboration, and continuous learning. Our machine learning engineers are encouraged to explore new algorithms, contribute to research papers, and stay updated with the latest advancements in AI. We value diversity and believe in creating a workplace that encourages innovation.',
      aboutValues: ['Curiosity', 'Collaboration', 'Continuous Learning', 'Innovation'],
      aboutPerks: ['On-site work environment', 'Professional development opportunities', 'Health and wellness programs'],
    },
  
    {
      logoImage:"https://media.licdn.com/dms/image/C560BAQHuSBi3DvXrOQ/company-logo_200_200/0/1630664189727/energy_innovation_network_logo?e=2147483647&v=beta&t=SqO7-MiRkSinOYDXF4OX-AEG7lsWg94_Ag5dEgP0KDE",
      id: 12,
      name: 'GreenEnergy Innovate',
      position: 'Renewable Energy Analyst',
      location: 'Netherlands (Remote)',
      responsibilities: ['Analyze renewable energy data', 'Contribute to sustainable energy projects'],
      qualifications: ['Degree in Renewable Energy or related field', 'Experience in energy analysis'],
      benefits: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
      employees: 90,
      projects: ['Project GreenEnergy - Renewable Energy Data Analysis', 'Project Sustainability - Eco-Friendly Energy Solutions'],
      achievements: [
        '2019 - Excellence in Renewable Energy Analysis',
        '2020 - Top Renewable Energy Analyst Team',
        '2021 - Innovation in Sustainable Energy'],
      foundedYear: 2016,
      website: 'https://www.greenenergyinnovate.com',
      contactEmail: 'info@greenenergyinnovate.com',
      technologiesUsed: ['GIS', 'Renewable Energy Modeling Software', 'Data Analytics Tools'],
      partnerships: ['Renewable Energy Association', 'Green Energy Council', 'Eco-friendly Technologies'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/greenenergyinnovate',
        twitter: 'https://twitter.com/greenenergyinnovate',
        facebook: 'https://www.facebook.com/greenenergyinnovate',
      },
      companySize: 'Medium',
      industry: 'Renewable Energy',
      awards: ['2022 - Top Renewable Energy Company', '2023 - Innovation in Clean Energy Solutions'],
      offices: [
        {
          city: 'Amsterdam',
          country: 'Netherlands',
        },
        {
          city: 'Rotterdam',
          country: 'Netherlands',
        },
      ],
      founders: ['Emma de Jong', 'Pieter van der Waals'],
      about: 'GreenEnergy Innovate is a leading company in the field of renewable energy, committed to analyzing and promoting sustainable energy solutions. Our team of renewable energy analysts is dedicated to advancing clean energy projects and contributing to a greener and more sustainable future. We embrace remote work and offer a collaborative and environmentally conscious workplace.',
      aboutCulture: 'At GreenEnergy Innovate, we foster a culture of sustainability, collaboration, and environmental responsibility. Our renewable energy analysts are encouraged to actively contribute to projects that promote clean energy and reduce environmental impact. We value diversity and believe in creating a workplace that aligns with our commitment to a greener planet.',
      aboutValues: ['Sustainability', 'Collaboration', 'Environmental Responsibility', 'Innovation in Clean Energy'],
      aboutPerks: ['Remote work options', 'Professional development opportunities', 'Health and wellness programs'],
    },
    {
      logoImage:"https://commercialisation.esa.int/wp-content/uploads/2023/02/BRE-logo-Yellow.jpg",
      id: 13,
      name: 'SpaceTech Explorations',
      position: 'Aerospace Engineer',
      location: 'Sweden (On-site)',
      responsibilities: ['Design and develop aerospace systems', 'Collaborate with space agencies'],
      qualifications: ['Degree in Aerospace Engineering', 'Experience in aerospace systems design'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 100,
      projects: ['Project Mars Mission - Spacecraft Design', 'Project Satellite Launch - Orbital Exploration'],
      achievements: [
        '2017 - Excellence in Aerospace Engineering',
        '2018 - Top Aerospace Engineering Team',
        '2019 - Innovation in Space Exploration'],
      foundedYear: 2014,
      website: 'https://www.spacetechexplorations.com',
      contactEmail: 'info@spacetechexplorations.com',
      technologiesUsed: ['CAD Software', 'Orbital Mechanics Simulation', 'Spacecraft Design Tools'],
      partnerships: ['NASA', 'ESA', 'SpaceX'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/spacetechexplorations',
        twitter: 'https://twitter.com/spacetechexplore',
        facebook: 'https://www.facebook.com/spacetechexplorations',
      },
      companySize: 'Large',
      industry: 'Aerospace Engineering',
      awards: ['2020 - Top Aerospace Engineering Company', '2021 - Innovation in Spacecraft Design'],
      offices: [
        {
          city: 'Stockholm',
          country: 'Sweden',
        },
        {
          city: 'Gothenburg',
          country: 'Sweden',
        },
      ],
      founders: ['Erik Andersson', 'Lena Berg'],
      about: 'SpaceTech Explorations is at the forefront of aerospace engineering, dedicated to designing and developing cutting-edge aerospace systems. Our team of aerospace engineers is passionate about pushing the boundaries of space exploration and contributing to advancements in space technology. We provide a collaborative and inspiring on-site work environment for our team.',
      aboutCulture: 'At SpaceTech Explorations, we foster a culture of innovation, collaboration, and passion for space exploration. Our aerospace engineers are encouraged to explore new ideas, contribute to groundbreaking projects, and stay updated with the latest advancements in aerospace technology. We value diversity and believe in creating a workplace that inspires creativity.',
      aboutValues: ['Innovation', 'Collaboration', 'Passion for Space Exploration', 'Continuous Learning'],
      aboutPerks: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
    {
      logoImage:"https://robotechsolutions.ae/wp-content/uploads/2019/02/cropped-RS-logo-website-1.png",
      id: 14,
      name: 'RoboTech Solutions',
      position: 'Robotics Engineer',
      location: 'Italy (On-site)',
      responsibilities: ['Design and develop robotic systems', 'Collaborate with engineering teams'],
      qualifications: ['Degree in Robotics or related field', 'Experience in robotics engineering'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 70,
      projects: ['Project RoboAssistant - Collaborative Robot Development', 'Project Automation - Industrial Robotics'],
      achievements: [
        '2019 - Top Robotics Engineering Team',
        '2020 - Innovation in Collaborative Robot Development',
        '2021 - Excellence in Industrial Robotics'],
      foundedYear: 2013,
      website: 'https://www.robotechsolutions.com',
      contactEmail: 'info@robotechsolutions.com',
      technologiesUsed: ['ROS (Robot Operating System)', 'CAD/CAM Software', 'Computer Vision'],
      partnerships: ['Robotics Industry Association', 'Universal Robots', 'ABB Robotics'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/robotechsolutions',
        twitter: 'https://twitter.com/robotechsolution',
        facebook: 'https://www.facebook.com/robotechsolutions',
      },
      companySize: 'Medium',
      industry: 'Robotics Engineering',
      awards: ['2022 - Top Robotics Engineering Company', '2023 - Innovation in Robot Design'],
      offices: [
        {
          city: 'Rome',
          country: 'Italy',
        },
        {
          city: 'Milan',
          country: 'Italy',
        },
      ],
      founders: ['Giovanni Rossi', 'Isabella Conti'],
      about: 'RoboTech Solutions specializes in robotics engineering, dedicated to designing and developing innovative robotic systems. Our team of robotics engineers is passionate about creating solutions that enhance automation and improve various industries. We provide an on-site work environment that fosters creativity and collaboration.',
      aboutCulture: 'At RoboTech Solutions, we foster a culture of innovation, collaboration, and a shared passion for robotics. Our robotics engineers are encouraged to explore new technologies, contribute to cutting-edge projects, and stay updated with the latest advancements in robotics engineering. We value diversity and believe in creating a workplace that inspires innovation.',
      aboutValues: ['Innovation', 'Collaboration', 'Passion for Robotics', 'Continuous Learning'],
      aboutPerks: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
  
    {
      logoImage:"https://hlttsolutions.com/wp-content/uploads/2023/01/HealthTech-Solutions-RGB.png",
      id: 15,
      name: 'HealthTech Solutions',
      position: 'Health Informatics Specialist',
      location: 'Denmark (On-site)',
      responsibilities: ['Analyze health data', 'Contribute to health informatics projects'],
      qualifications: ['Degree in Health Informatics or related field', 'Experience in health data analysis'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 85,
      projects: ['Project HealthData - Electronic Health Record Analysis', 'Project Telemedicine - Remote Health Monitoring'],
      achievements: [
        '2018 - Top Health Informatics Team',
        '2019 - Excellence in EHR Analysis',
        '2020 - Innovation in Telemedicine Solutions'],
      foundedYear: 2015,
      website: 'https://www.healthtechsolutions.com',
      contactEmail: 'info@healthtechsolutions.com',
      technologiesUsed: ['Health Informatics Software', 'Data Analytics Tools', 'Telehealth Platforms'],
      partnerships: ['World Health Organization', 'National Health Service', 'Health Informatics Association'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/healthtechsolutions',
        twitter: 'https://twitter.com/healthtechsol',
        facebook: 'https://www.facebook.com/healthtechsolutions',
      },
      companySize: 'Medium',
      industry: 'Health Informatics',
      awards: ['2021 - Top Health Informatics Company', '2022 - Innovation in Telehealth'],
      offices: [
        {
          city: 'Copenhagen',
          country: 'Denmark',
        },
        {
          city: 'Aarhus',
          country: 'Denmark',
        },
      ],
      founders: ['Morten Nielsen', 'Lise Andersen'],
      about: 'HealthTech Solutions is a leader in health informatics, specializing in analyzing health data and contributing to innovative health informatics projects. Our team of health informatics specialists is dedicated to improving healthcare through data-driven insights and technology solutions. We offer an on-site work environment that prioritizes employee well-being.',
      aboutCulture: 'At HealthTech Solutions, we foster a culture of innovation, collaboration, and a shared commitment to improving healthcare. Our health informatics specialists are encouraged to explore new methodologies, contribute to impactful projects, and stay updated with the latest trends in health informatics. We value diversity and believe in creating a workplace that supports the well-being of our team.',
      aboutValues: ['Innovation', 'Collaboration', 'Improving Healthcare', 'Data-Driven Insights'],
      aboutPerks: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
  
    {
      logoImage:"https://euhubs4data.eu/wp-content/uploads/2021/11/Logo-CIH.png",
      id: 16,
      name: 'CyberSec Innovations',
      position: 'Cybersecurity Analyst',
      location: 'Switzerland (Remote)',
      responsibilities: ['Analyze and implement cybersecurity measures', 'Collaborate with IT teams'],
      qualifications: ['Degree in Cybersecurity or related field', 'Experience in cybersecurity analysis'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
      employees: 50,
      projects: ['Project CyberShield - Advanced Threat Detection', 'Project SecureNetwork - Network Security Enhancement'],
      achievements: [
        '2019 - Top Cybersecurity Team',
        '2020 - Excellence in Cybersecurity Analysis',
        '2021 - Innovation in Threat Detection'],
      foundedYear: 2012,
      website: 'https://www.cybersecinnovations.com',
      contactEmail: 'info@cybersecinnovations.com',
      technologiesUsed: ['SIEM Solutions', 'Firewall Technologies', 'Intrusion Detection Systems'],
      partnerships: ['Cybersecurity Alliance', 'International Association of Privacy Professionals', 'ISC(2)'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/cybersecinnovations',
        twitter: 'https://twitter.com/cybersecinnov',
        facebook: 'https://www.facebook.com/cybersecinnovations',
      },
      companySize: 'Small',
      industry: 'Cybersecurity',
      awards: ['2022 - Top Cybersecurity Company', '2023 - Innovation in Network Security'],
      about: 'CyberSec Innovations is a cybersecurity firm specializing in advanced threat detection and network security. Our team of cybersecurity analysts is committed to safeguarding digital assets and providing cutting-edge solutions to address evolving cybersecurity challenges. We offer remote work flexibility and prioritize professional development for our team.',
      aboutCulture: 'At CyberSec Innovations, we foster a culture of excellence, collaboration, and adaptability to stay ahead in the ever-changing field of cybersecurity. Our cybersecurity analysts are encouraged to explore new technologies, contribute to impactful projects, and pursue continuous learning. We value diversity and believe in creating a flexible and dynamic workplace.',
      aboutValues: ['Excellence', 'Collaboration', 'Adaptability', 'Continuous Learning'],
      aboutPerks: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
    },
    {
      logoImage:"https://www.shutterstock.com/image-vector/blockchain-logo-icon-vector-isolated-600nw-1522458983.jpg",
      id: 17,
      name: 'Blockchain Innovators',
      position: 'Blockchain Developer',
      location: 'Norway (Remote)',
      responsibilities: ['Develop blockchain applications', 'Collaborate with blockchain experts'],
      qualifications: ['Proficiency in blockchain development', 'Experience with blockchain frameworks'],
      benefits: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
      employees: 60,
      projects: ['Project BlockChainApp - Decentralized Application Development', 'Project CryptoSmart - Cryptocurrency Solutions'],
      achievements: [
        '2020 - Top Blockchain Developer Team',
        '2021 - Innovation in Decentralized Application Development',
        '2022 - Excellence in Cryptocurrency Solutions'],
      foundedYear: 2016,
      website: 'https://www.blockchaininnovators.com',
      contactEmail: 'info@blockchaininnovators.com',
      technologiesUsed: ['Smart Contracts', 'Distributed Ledger Technology', 'Blockchain Platforms'],
      partnerships: ['Blockchain Industry Association', 'Ethereum Foundation', 'Hyperledger'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/blockchaininnovators',
        twitter: 'https://twitter.com/blockchaininnov',
        facebook: 'https://www.facebook.com/blockchaininnovators',
      },
      companySize: 'Medium',
      industry: 'Blockchain Development',
      awards: ['2023 - Top Blockchain Development Company', '2024 - Innovation in Cryptocurrency Solutions'],
      offices: [
        {
          city: 'Oslo',
          country: 'Norway',
        },
        {
          city: 'Bergen',
          country: 'Norway',
        },
      ],
      founders: ['Lars Andersen', 'Ingrid Larsen'],
      about: 'Blockchain Innovators is at the forefront of blockchain development, specializing in decentralized application development and cryptocurrency solutions. Our team of blockchain developers is dedicated to pushing the boundaries of blockchain technology and creating innovative solutions for various industries. We offer remote work options and prioritize professional development opportunities for our team.',
      aboutCulture: 'At Blockchain Innovators, we foster a culture of innovation, collaboration, and continuous learning in the dynamic field of blockchain development. Our developers are encouraged to explore emerging technologies, contribute to groundbreaking projects, and stay updated with the latest trends in blockchain. We value diversity and believe in creating an inclusive and forward-thinking workplace.',
      aboutValues: ['Innovation', 'Collaboration', 'Continuous Learning', 'Diversity and Inclusion'],
      aboutPerks: ['Remote work options', 'Competitive salary', 'Professional development opportunities'],
    },
  
    {
      logoImage:"https://images.squarespace-cdn.com/content/v1/6516b0c4cdba01348b741c2f/186955d8-f269-4482-9297-f71d34f03a4e/EdTech+Innovate+London+24+logo+medium+colour+no+date.png",
      id: 18,
      name: 'EdTech Innovate',
      position: 'Educational Technologist',
      location: 'Finland (Remote)',
      responsibilities: ['Develop educational technology solutions', 'Collaborate with educators'],
      qualifications: ['Proficiency in educational technology', 'Experience in edtech development'],
      benefits: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
      employees: 45,
      projects: ['Project EduTechPlus - Interactive Learning Platforms', 'Project VirtualClassroom - Virtual Learning Environments'],
      achievements: [
        '2019 - Top EdTech Developer Team',
        '2020 - Excellence in Interactive Learning Platforms',
        '2021 - Innovation in Virtual Learning Environments'],
      foundedYear: 2014,
      website: 'https://www.edtechinnovate.com',
      contactEmail: 'info@edtechinnovate.com',
      technologiesUsed: ['Learning Management Systems', 'Interactive Learning Tools', 'Virtual Reality in Education'],
      partnerships: ['International Society for Technology in Education', 'EdSurge', 'Google for Education'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/edtechinnovate',
        twitter: 'https://twitter.com/edtechinnov',
        facebook: 'https://www.facebook.com/edtechinnovate',
      },
      companySize: 'Small',
      industry: 'Educational Technology',
      awards: ['2022 - Top EdTech Company', '2023 - Innovation in Virtual Learning Solutions'],
      offices: [
        {
          city: 'Helsinki',
          country: 'Finland',
        },
        {
          city: 'Tampere',
          country: 'Finland',
        },
      ],
      founders: ['Mika Virtanen', 'Elina Hakkinen'],
      about: 'EdTech Innovate is a leader in educational technology, focusing on developing innovative solutions for interactive learning and virtual classrooms. Our team of educational technologists is passionate about transforming education through technology. We offer remote work flexibility and prioritize professional development opportunities for our team.',
      aboutCulture: 'At EdTech Innovate, we cultivate a culture of innovation, collaboration, and a shared commitment to improving education through technology. Our educational technologists are encouraged to explore creative solutions, contribute to impactful projects, and stay updated with the latest trends in edtech. We value diversity and believe in creating a supportive and dynamic workplace.',
      aboutValues: ['Innovation', 'Collaboration', 'Improving Education', 'Continuous Learning'],
      aboutPerks: ['Remote work flexibility', 'Competitive salary', 'Professional development opportunities'],
    },
  
    {
      logoImage:"https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/04575f91fefe7dfd330c",
      id: 19,
      name: 'CleanTech Solutions',
      position: 'Environmental Engineer',
      location: 'Iceland (On-site)',
      responsibilities: ['Design and implement environmental solutions', 'Collaborate with environmental scientists'],
      qualifications: ['Degree in Environmental Engineering or related field', 'Experience in environmental engineering'],
      benefits: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
      employees: 55,
      projects: ['Project EcoSolutions - Sustainable Environmental Solutions', 'Project GreenCities - Urban Green Planning'],
      achievements: [
        '2020 - Top Environmental Engineering Team',
        '2021 - Excellence in Sustainable Solutions',
        '2022 - Innovation in Urban Green Planning'],
      foundedYear: 2015,
      website: 'https://www.cleantechsolutions.com',
      contactEmail: 'info@cleantechsolutions.com',
      technologiesUsed: ['Environmental Modeling Software', 'Sustainable Design Tools', 'Urban Planning Software'],
      partnerships: ['Environmental and Energy Study Institute', 'International Society for Environmental Planning', 'Green Building Council'],
      socialMedia: {
        linkedin: 'https://www.linkedin.com/company/cleantechsolutions',
        twitter: 'https://twitter.com/cleantechsol',
        facebook: 'https://www.facebook.com/cleantechsolutions',
      },
      companySize: 'Medium',
      industry: 'Environmental Engineering',
      awards: ['2023 - Top Environmental Engineering Company', '2024 - Innovation in Sustainable Solutions'],
      offices: [
        {
          city: 'Reykjavik',
          country: 'Iceland',
        },
        {
          city: 'Akureyri',
          country: 'Iceland',
        },
      ],
      founders: ['Sigurdur Jonsson', 'Elin Magnusdottir'],
      about: 'CleanTech Solutions specializes in environmental engineering, offering sustainable solutions and innovative approaches to address environmental challenges. Our team of environmental engineers is dedicated to creating a positive impact on the planet. We provide an on-site work environment and prioritize the well-being of our employees.',
      aboutCulture: 'At CleanTech Solutions, we foster a culture of sustainability, collaboration, and a shared commitment to environmental stewardship. Our environmental engineers are encouraged to contribute to meaningful projects, engage in community initiatives, and pursue continuous learning. We value diversity and believe in creating a green and inclusive workplace.',
      aboutValues: ['Sustainability', 'Collaboration', 'Environmental Stewardship', 'Continuous Learning'],
      aboutPerks: ['On-site work environment', 'Competitive salary', 'Health and wellness programs'],
    },
  ];
  
export default companies;  